Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: logs
  LogFileName: deploy-agent
  LogFileExt: .log
  DeployPath:
    - ../tech/deploy-agent
    - ../tech/deploy-test
  DeployFiles:
    - aaa.txt
    - bbb.xml
  ExecScripts:
    - startbb.sh
    - start.sh
    - start.sh error
    - start.sh aaa
  UploadMaxSize: 500  # MB
  UploadAllowExts:
    - .txt
    - .xml
    - .sh
